### ISSUE TITLE
Error status 400 in requests both to RAWG and Steam

### ISSUE THREAD

**Issue by daleao** [CMorooney/obsidian-game-search-plugin#44]
I've read some closed issues explaining the delay with RAWG accepting requests from new API keys.
However I also get similar errors when trying to sync to Steam.

Console output:
```
[Game Search][Info] version 0.2.12 (requires obsidian 0.15.0)
plugin:game-search:15 [Game Search][Steam Sync]: initializing steam api
plugin:game-search:10 [Game Search][Steam Sync]: fetching owned games from steam api
plugin:game-search:10 [Game Search][Steam API][getOwnedGames]Error: Request failed, status 400
eval @ plugin:game-search:10
app.js:1 Uncaught (in promise) Error: Request failed, status 400
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
plugin:game-search:10 [Game Search][Steam Sync]: fetching owned games from steam api
plugin:game-search:10 [Game Search][Steam API][getOwnedGames]Error: Request failed, status 400
eval @ plugin:game-search:10
app.js:1 Uncaught (in promise) Error: Request failed, status 400
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
plugin:game-search:10 [Game Search][Steam API][getOwnedGames]Error: Request failed, status 400
eval @ plugin:game-search:10
plugin:game-search:10 [Game Search][Steam API][tryGetGame]Error: Request failed, status 400
eval @ plugin:game-search:10
plugin:game-search:15 [Game Search][Create Game Note][unexpected] Error: Request failed, status 400
eval @ plugin:game-search:15
```

Current app version 1.6.7
Installer version 1.5.3

Steam library set to Public.

**Comment by breakid** [comment]
@daleao 

1. Are you still getting this error?
2. Have you updated to the latest versions of Obsidian and the Game Search plugin?
    - I just successfully synced with Steam using the following (latest) versions:
        - Obsidian Version: 1.7.4
        - Obsidian Installer Version: 1.5.3
        - Game Search Version: 0.2.12
3. Have you ever successfully synced with Steam, or has this never worked for you?
    - If it worked previously and suddenly stopped working, I'd suggest regenerating your Steam API key
        - I'm not sure whether they expire or what behavior it might cause if they do
    - If it never worked, I'd suggest double checking your Steam ID and Steam API key (e.g., making sure there are no leading or trailing spaces, etc.)

**Comment by Edeherz** [comment]
When you have your Vault in Onedrive you need to disable "Dev Drive Protection" under Windows Security -> virus threat protection -> Settings -> Dev Drive Protection

**Comment by CMorooney** [comment]
@daleao any updates?

**Comment by CMorooney** [comment]
closing since there is no response
